package goorm.eagle7.stelligence.domain.member.model;

public enum Badge {
	WELCOME, SUN, MOON, STAR, CLOUD, RAIN, SNOW, WIND, THUNDER, LIGHTNING, RAINBOW, FOG, HAIL, SLEET, TORNADO, EARTHQUAKE, VOLCANO, TSUNAMI, AVALANCHE, FLOOD, DROUGHT, FIRE, HURRICANE, TYPHOON, BLIZZARD, METEOR, COMET, ASTEROID, GALAXY, UNIVERSE, COSMOS, BLACKHOLE, BIGBANG
}
