version: '3'

services:
  mysql:
    image: mysql:8.0.30
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: stelligence
      MYSQL_PASSWORD: 12345678
      TZ: Asia/Seoul
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    networks:
      - local_network

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: none
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    networks:
      - local_network

  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --maxmemory 500mb --maxmemory-policy volatile-lru
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
    networks:
      - local_network

networks:
  local_network:
