package goorm.eagle7.stelligence.domain.document.content.dto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Heading.proto

/**
 * ProtoBuf을 사용한 Heading DTO 클래스의 외부 클래스입니다.
 * 코드 전반으로 사용되는 코드를 보기 위해서는 내부 클래스인 Heading를 확인해주세요.
 */
public final class HeadingOuterClass {
	private HeadingOuterClass() {
	}

	public static void registerAllExtensions(
		com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(
		com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions(
			(com.google.protobuf.ExtensionRegistryLite)registry);
	}

	/**
	 * Protobuf enum {@code Heading}
	 */
	public enum Heading
		implements com.google.protobuf.ProtocolMessageEnum {
		/**
		 * <code>H1 = 0;</code>
		 */
		H1(0),
		/**
		 * <code>H2 = 1;</code>
		 */
		H2(1),
		/**
		 * <code>H3 = 2;</code>
		 */
		H3(2),
		/**
		 * <code>H4 = 3;</code>
		 */
		H4(3),
		/**
		 * <code>H5 = 4;</code>
		 */
		H5(4),
		/**
		 * <code>H6 = 5;</code>
		 */
		H6(5),
		UNRECOGNIZED(-1),
		;

		/**
		 * <code>H1 = 0;</code>
		 */
		public static final int H1_VALUE = 0;
		/**
		 * <code>H2 = 1;</code>
		 */
		public static final int H2_VALUE = 1;
		/**
		 * <code>H3 = 2;</code>
		 */
		public static final int H3_VALUE = 2;
		/**
		 * <code>H4 = 3;</code>
		 */
		public static final int H4_VALUE = 3;
		/**
		 * <code>H5 = 4;</code>
		 */
		public static final int H5_VALUE = 4;
		/**
		 * <code>H6 = 5;</code>
		 */
		public static final int H6_VALUE = 5;

		public final int getNumber() {
			if (this == UNRECOGNIZED) {
				throw new java.lang.IllegalArgumentException(
					"Can't get the number of an unknown enum value.");
			}
			return value;
		}

		/**
		 * @deprecated Use {@link #forNumber(int)} instead.
		 */
		@java.lang.Deprecated
		public static Heading valueOf(int value) {
			return forNumber(value);
		}

		public static Heading forNumber(int value) {
			switch (value) {
				case 0:
					return H1;
				case 1:
					return H2;
				case 2:
					return H3;
				case 3:
					return H4;
				case 4:
					return H5;
				case 5:
					return H6;
				default:
					return null;
			}
		}

		public static com.google.protobuf.Internal.EnumLiteMap<Heading>
		internalGetValueMap() {
			return internalValueMap;
		}

		private static final com.google.protobuf.Internal.EnumLiteMap<
			Heading> internalValueMap =
			new com.google.protobuf.Internal.EnumLiteMap<Heading>() {
				public Heading findValueByNumber(int number) {
					return Heading.forNumber(number);
				}
			};

		public final com.google.protobuf.Descriptors.EnumValueDescriptor
		getValueDescriptor() {
			return getDescriptor().getValues().get(ordinal());
		}

		public final com.google.protobuf.Descriptors.EnumDescriptor
		getDescriptorForType() {
			return getDescriptor();
		}

		public static final com.google.protobuf.Descriptors.EnumDescriptor
		getDescriptor() {
			return HeadingOuterClass.getDescriptor().getEnumTypes().get(0);
		}

		private static final Heading[] VALUES = values();

		public static Heading valueOf(
			com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
			if (desc.getType() != getDescriptor()) {
				throw new java.lang.IllegalArgumentException(
					"EnumValueDescriptor is not for this type.");
			}
			if (desc.getIndex() == -1) {
				return UNRECOGNIZED;
			}
			return VALUES[desc.getIndex()];
		}

		private final int value;

		private Heading(int value) {
			this.value = value;
		}

		// @@protoc_insertion_point(enum_scope:Heading)
	}

	public static com.google.protobuf.Descriptors.FileDescriptor
	getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor
		descriptor;

	static {
		java.lang.String[] descriptorData = {
			"\n\rHeading.proto*9\n\007Heading\022\006\n\002H1\020\000\022\006\n\002H2" +
				"\020\001\022\006\n\002H3\020\002\022\006\n\002H4\020\003\022\006\n\002H5\020\004\022\006\n\002H6\020\005b\006prot"
				+
				"o3"
		};
		descriptor = com.google.protobuf.Descriptors.FileDescriptor
			.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {
				});
	}

	// @@protoc_insertion_point(outer_class_scope)
}
