package goorm.eagle7.stelligence.domain.document.content.dto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SectionResponse.proto

import goorm.eagle7.stelligence.domain.section.model.Section;

/**
 * ProtoBuf을 사용한 SectionResponse DTO 클래스의 외부 클래스입니다.
 * 코드 전반으로 사용되는 코드를 보기 위해서는 내부 클래스인 SectionResponse를 확인해주세요.
 */
public final class SectionResponseOuterClass {
	private SectionResponseOuterClass() {
	}

	public static void registerAllExtensions(
		com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(
		com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions(
			(com.google.protobuf.ExtensionRegistryLite)registry);
	}

	public interface SectionResponseOrBuilder extends
		// @@protoc_insertion_point(interface_extends:SectionResponse)
		com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>int64 sectionId = 1;</code>
		 */
		long getSectionId();

		/**
		 * <code>int64 revision = 2;</code>
		 */
		long getRevision();

		/**
		 * <code>.Heading heading = 3;</code>
		 */
		int getHeadingValue();

		/**
		 * <code>.Heading heading = 3;</code>
		 */
		HeadingOuterClass.Heading getHeading();

		/**
		 * <code>string title = 4;</code>
		 */
		java.lang.String getTitle();

		/**
		 * <code>string title = 4;</code>
		 */
		com.google.protobuf.ByteString
		getTitleBytes();

		/**
		 * <code>string content = 5;</code>
		 */
		java.lang.String getContent();

		/**
		 * <code>string content = 5;</code>
		 */
		com.google.protobuf.ByteString
		getContentBytes();
	}

	/**
	 * Protobuf type {@code SectionResponse}
	 */
	public static final class SectionResponse extends
		com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:SectionResponse)
		SectionResponseOrBuilder {
		private static final long serialVersionUID = 0L;

		//factory method
		public static SectionResponse of(Section section) {
			return SectionResponse.newBuilder()
				.setSectionId(section.getId())
				.setRevision(section.getRevision())
				.setHeading(HeadingOuterClass.Heading.valueOf(section.getHeading().name()))
				.setTitle(section.getTitle())
				.setContent(section.getContent())
				.build();
		}

		// Use SectionResponse.newBuilder() to construct.
		private SectionResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private SectionResponse() {
			heading_ = 0;
			title_ = "";
			content_ = "";
		}

		@java.lang.Override
		@SuppressWarnings({"unused"})
		protected java.lang.Object newInstance(
			UnusedPrivateParameter unused) {
			return new SectionResponse();
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet
		getUnknownFields() {
			return this.unknownFields;
		}

		private SectionResponse(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new java.lang.NullPointerException();
			}
			com.google.protobuf.UnknownFieldSet.Builder unknownFields =
				com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						case 8: {

							sectionId_ = input.readInt64();
							break;
						}
						case 16: {

							revision_ = input.readInt64();
							break;
						}
						case 24: {
							int rawValue = input.readEnum();

							heading_ = rawValue;
							break;
						}
						case 34: {
							java.lang.String s = input.readStringRequireUtf8();

							title_ = s;
							break;
						}
						case 42: {
							java.lang.String s = input.readStringRequireUtf8();

							content_ = s;
							break;
						}
						default: {
							if (!parseUnknownField(
								input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
					e).setUnfinishedMessage(this);
			} finally {
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor
		getDescriptor() {
			return SectionResponseOuterClass.internal_static_SectionResponse_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
		internalGetFieldAccessorTable() {
			return SectionResponseOuterClass.internal_static_SectionResponse_fieldAccessorTable
				.ensureFieldAccessorsInitialized(
					SectionResponseOuterClass.SectionResponse.class,
					SectionResponseOuterClass.SectionResponse.Builder.class);
		}

		public static final int SECTIONID_FIELD_NUMBER = 1;
		private long sectionId_;

		/**
		 * <code>int64 sectionId = 1;</code>
		 */
		public long getSectionId() {
			return sectionId_;
		}

		public static final int REVISION_FIELD_NUMBER = 2;
		private long revision_;

		/**
		 * <code>int64 revision = 2;</code>
		 */
		public long getRevision() {
			return revision_;
		}

		public static final int HEADING_FIELD_NUMBER = 3;
		private int heading_;

		/**
		 * <code>.Heading heading = 3;</code>
		 */
		public int getHeadingValue() {
			return heading_;
		}

		/**
		 * <code>.Heading heading = 3;</code>
		 */
		public HeadingOuterClass.Heading getHeading() {
			@SuppressWarnings("deprecation")
			HeadingOuterClass.Heading result = HeadingOuterClass.Heading.valueOf(heading_);
			return result == null ? HeadingOuterClass.Heading.UNRECOGNIZED : result;
		}

		public static final int TITLE_FIELD_NUMBER = 4;
		private volatile java.lang.Object title_;

		/**
		 * <code>string title = 4;</code>
		 */
		public java.lang.String getTitle() {
			java.lang.Object ref = title_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String)ref;
			} else {
				com.google.protobuf.ByteString bs =
					(com.google.protobuf.ByteString)ref;
				java.lang.String s = bs.toStringUtf8();
				title_ = s;
				return s;
			}
		}

		/**
		 * <code>string title = 4;</code>
		 */
		public com.google.protobuf.ByteString
		getTitleBytes() {
			java.lang.Object ref = title_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b =
					com.google.protobuf.ByteString.copyFromUtf8(
						(java.lang.String)ref);
				title_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString)ref;
			}
		}

		public static final int CONTENT_FIELD_NUMBER = 5;
		private volatile java.lang.Object content_;

		/**
		 * <code>string content = 5;</code>
		 */
		public java.lang.String getContent() {
			java.lang.Object ref = content_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String)ref;
			} else {
				com.google.protobuf.ByteString bs =
					(com.google.protobuf.ByteString)ref;
				java.lang.String s = bs.toStringUtf8();
				content_ = s;
				return s;
			}
		}

		/**
		 * <code>string content = 5;</code>
		 */
		public com.google.protobuf.ByteString
		getContentBytes() {
			java.lang.Object ref = content_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b =
					com.google.protobuf.ByteString.copyFromUtf8(
						(java.lang.String)ref);
				content_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString)ref;
			}
		}

		private byte memoizedIsInitialized = -1;

		@java.lang.Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@java.lang.Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
			throws java.io.IOException {
			if (sectionId_ != 0L) {
				output.writeInt64(1, sectionId_);
			}
			if (revision_ != 0L) {
				output.writeInt64(2, revision_);
			}
			if (heading_ != HeadingOuterClass.Heading.H1.getNumber()) {
				output.writeEnum(3, heading_);
			}
			if (!getTitleBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 4, title_);
			}
			if (!getContentBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 5, content_);
			}
			unknownFields.writeTo(output);
		}

		@java.lang.Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			if (sectionId_ != 0L) {
				size += com.google.protobuf.CodedOutputStream
					.computeInt64Size(1, sectionId_);
			}
			if (revision_ != 0L) {
				size += com.google.protobuf.CodedOutputStream
					.computeInt64Size(2, revision_);
			}
			if (heading_ != HeadingOuterClass.Heading.H1.getNumber()) {
				size += com.google.protobuf.CodedOutputStream
					.computeEnumSize(3, heading_);
			}
			if (!getTitleBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, title_);
			}
			if (!getContentBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, content_);
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof SectionResponseOuterClass.SectionResponse)) {
				return super.equals(obj);
			}
			SectionResponseOuterClass.SectionResponse other = (SectionResponseOuterClass.SectionResponse)obj;

			if (getSectionId()
				!= other.getSectionId())
				return false;
			if (getRevision()
				!= other.getRevision())
				return false;
			if (heading_ != other.heading_)
				return false;
			if (!getTitle()
				.equals(other.getTitle()))
				return false;
			if (!getContent()
				.equals(other.getContent()))
				return false;
			if (!unknownFields.equals(other.unknownFields))
				return false;
			return true;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + SECTIONID_FIELD_NUMBER;
			hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
				getSectionId());
			hash = (37 * hash) + REVISION_FIELD_NUMBER;
			hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
				getRevision());
			hash = (37 * hash) + HEADING_FIELD_NUMBER;
			hash = (53 * hash) + heading_;
			hash = (37 * hash) + TITLE_FIELD_NUMBER;
			hash = (53 * hash) + getTitle().hashCode();
			hash = (37 * hash) + CONTENT_FIELD_NUMBER;
			hash = (53 * hash) + getContent().hashCode();
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static SectionResponseOuterClass.SectionResponse parseFrom(
			java.nio.ByteBuffer data)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static SectionResponseOuterClass.SectionResponse parseFrom(
			java.nio.ByteBuffer data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static SectionResponseOuterClass.SectionResponse parseFrom(
			com.google.protobuf.ByteString data)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static SectionResponseOuterClass.SectionResponse parseFrom(
			com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static SectionResponseOuterClass.SectionResponse parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static SectionResponseOuterClass.SectionResponse parseFrom(
			byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static SectionResponseOuterClass.SectionResponse parseFrom(java.io.InputStream input)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input);
		}

		public static SectionResponseOuterClass.SectionResponse parseFrom(
			java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static SectionResponseOuterClass.SectionResponse parseDelimitedFrom(java.io.InputStream input)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseDelimitedWithIOException(PARSER, input);
		}

		public static SectionResponseOuterClass.SectionResponse parseDelimitedFrom(
			java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static SectionResponseOuterClass.SectionResponse parseFrom(
			com.google.protobuf.CodedInputStream input)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input);
		}

		public static SectionResponseOuterClass.SectionResponse parseFrom(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@java.lang.Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(SectionResponseOuterClass.SectionResponse prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@java.lang.Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE
				? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
			com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code SectionResponse}
		 */
		public static final class Builder extends
			com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:SectionResponse)
			SectionResponseOuterClass.SectionResponseOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return SectionResponseOuterClass.internal_static_SectionResponse_descriptor;
			}

			@java.lang.Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internalGetFieldAccessorTable() {
				return SectionResponseOuterClass.internal_static_SectionResponse_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
						SectionResponseOuterClass.SectionResponse.class,
						SectionResponseOuterClass.SectionResponse.Builder.class);
			}

			// Construct using SectionResponseOuterClass.SectionResponse.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
				com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3
					.alwaysUseFieldBuilders) {
				}
			}

			@java.lang.Override
			public Builder clear() {
				super.clear();
				sectionId_ = 0L;

				revision_ = 0L;

				heading_ = 0;

				title_ = "";

				content_ = "";

				return this;
			}

			@java.lang.Override
			public com.google.protobuf.Descriptors.Descriptor
			getDescriptorForType() {
				return SectionResponseOuterClass.internal_static_SectionResponse_descriptor;
			}

			@java.lang.Override
			public SectionResponseOuterClass.SectionResponse getDefaultInstanceForType() {
				return SectionResponseOuterClass.SectionResponse.getDefaultInstance();
			}

			@java.lang.Override
			public SectionResponseOuterClass.SectionResponse build() {
				SectionResponseOuterClass.SectionResponse result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@java.lang.Override
			public SectionResponseOuterClass.SectionResponse buildPartial() {
				SectionResponseOuterClass.SectionResponse result = new SectionResponseOuterClass.SectionResponse(this);
				result.sectionId_ = sectionId_;
				result.revision_ = revision_;
				result.heading_ = heading_;
				result.title_ = title_;
				result.content_ = content_;
				onBuilt();
				return result;
			}

			@java.lang.Override
			public Builder clone() {
				return super.clone();
			}

			@java.lang.Override
			public Builder setField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				java.lang.Object value) {
				return super.setField(field, value);
			}

			@java.lang.Override
			public Builder clearField(
				com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}

			@java.lang.Override
			public Builder clearOneof(
				com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}

			@java.lang.Override
			public Builder setRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				int index, java.lang.Object value) {
				return super.setRepeatedField(field, index, value);
			}

			@java.lang.Override
			public Builder addRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				java.lang.Object value) {
				return super.addRepeatedField(field, value);
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof SectionResponseOuterClass.SectionResponse) {
					return mergeFrom((SectionResponseOuterClass.SectionResponse)other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(SectionResponseOuterClass.SectionResponse other) {
				if (other == SectionResponseOuterClass.SectionResponse.getDefaultInstance())
					return this;
				if (other.getSectionId() != 0L) {
					setSectionId(other.getSectionId());
				}
				if (other.getRevision() != 0L) {
					setRevision(other.getRevision());
				}
				if (other.heading_ != 0) {
					setHeadingValue(other.getHeadingValue());
				}
				if (!other.getTitle().isEmpty()) {
					title_ = other.title_;
					onChanged();
				}
				if (!other.getContent().isEmpty()) {
					content_ = other.content_;
					onChanged();
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			@java.lang.Override
			public final boolean isInitialized() {
				return true;
			}

			@java.lang.Override
			public Builder mergeFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
				SectionResponseOuterClass.SectionResponse parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (SectionResponseOuterClass.SectionResponse)e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private long sectionId_;

			/**
			 * <code>int64 sectionId = 1;</code>
			 */
			public long getSectionId() {
				return sectionId_;
			}

			/**
			 * <code>int64 sectionId = 1;</code>
			 */
			public Builder setSectionId(long value) {

				sectionId_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>int64 sectionId = 1;</code>
			 */
			public Builder clearSectionId() {

				sectionId_ = 0L;
				onChanged();
				return this;
			}

			private long revision_;

			/**
			 * <code>int64 revision = 2;</code>
			 */
			public long getRevision() {
				return revision_;
			}

			/**
			 * <code>int64 revision = 2;</code>
			 */
			public Builder setRevision(long value) {

				revision_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>int64 revision = 2;</code>
			 */
			public Builder clearRevision() {

				revision_ = 0L;
				onChanged();
				return this;
			}

			private int heading_ = 0;

			/**
			 * <code>.Heading heading = 3;</code>
			 */
			public int getHeadingValue() {
				return heading_;
			}

			/**
			 * <code>.Heading heading = 3;</code>
			 */
			public Builder setHeadingValue(int value) {
				heading_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>.Heading heading = 3;</code>
			 */
			public HeadingOuterClass.Heading getHeading() {
				@SuppressWarnings("deprecation")
				HeadingOuterClass.Heading result = HeadingOuterClass.Heading.valueOf(heading_);
				return result == null ? HeadingOuterClass.Heading.UNRECOGNIZED : result;
			}

			/**
			 * <code>.Heading heading = 3;</code>
			 */
			public Builder setHeading(HeadingOuterClass.Heading value) {
				if (value == null) {
					throw new NullPointerException();
				}

				heading_ = value.getNumber();
				onChanged();
				return this;
			}

			/**
			 * <code>.Heading heading = 3;</code>
			 */
			public Builder clearHeading() {

				heading_ = 0;
				onChanged();
				return this;
			}

			private java.lang.Object title_ = "";

			/**
			 * <code>string title = 4;</code>
			 */
			public java.lang.String getTitle() {
				java.lang.Object ref = title_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString)ref;
					java.lang.String s = bs.toStringUtf8();
					title_ = s;
					return s;
				} else {
					return (java.lang.String)ref;
				}
			}

			/**
			 * <code>string title = 4;</code>
			 */
			public com.google.protobuf.ByteString
			getTitleBytes() {
				java.lang.Object ref = title_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
							(java.lang.String)ref);
					title_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString)ref;
				}
			}

			/**
			 * <code>string title = 4;</code>
			 */
			public Builder setTitle(
				java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				title_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string title = 4;</code>
			 */
			public Builder clearTitle() {

				title_ = getDefaultInstance().getTitle();
				onChanged();
				return this;
			}

			/**
			 * <code>string title = 4;</code>
			 */
			public Builder setTitleBytes(
				com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				title_ = value;
				onChanged();
				return this;
			}

			private java.lang.Object content_ = "";

			/**
			 * <code>string content = 5;</code>
			 */
			public java.lang.String getContent() {
				java.lang.Object ref = content_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString)ref;
					java.lang.String s = bs.toStringUtf8();
					content_ = s;
					return s;
				} else {
					return (java.lang.String)ref;
				}
			}

			/**
			 * <code>string content = 5;</code>
			 */
			public com.google.protobuf.ByteString
			getContentBytes() {
				java.lang.Object ref = content_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
							(java.lang.String)ref);
					content_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString)ref;
				}
			}

			/**
			 * <code>string content = 5;</code>
			 */
			public Builder setContent(
				java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				content_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string content = 5;</code>
			 */
			public Builder clearContent() {

				content_ = getDefaultInstance().getContent();
				onChanged();
				return this;
			}

			/**
			 * <code>string content = 5;</code>
			 */
			public Builder setContentBytes(
				com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				content_ = value;
				onChanged();
				return this;
			}

			@java.lang.Override
			public final Builder setUnknownFields(
				final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFields(unknownFields);
			}

			@java.lang.Override
			public final Builder mergeUnknownFields(
				final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:SectionResponse)
		}

		// @@protoc_insertion_point(class_scope:SectionResponse)
		private static final SectionResponseOuterClass.SectionResponse DEFAULT_INSTANCE;

		static {
			DEFAULT_INSTANCE = new SectionResponseOuterClass.SectionResponse();
		}

		public static SectionResponseOuterClass.SectionResponse getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<SectionResponse>
			PARSER = new com.google.protobuf.AbstractParser<SectionResponse>() {
			@java.lang.Override
			public SectionResponse parsePartialFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
				return new SectionResponse(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<SectionResponse> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<SectionResponse> getParserForType() {
			return PARSER;
		}

		@java.lang.Override
		public SectionResponseOuterClass.SectionResponse getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor
		internal_static_SectionResponse_descriptor;
	private static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
		internal_static_SectionResponse_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor
	getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor
		descriptor;

	static {
		java.lang.String[] descriptorData = {
			"\n\025SectionResponse.proto\032\rHeading.proto\"q" +
				"\n\017SectionResponse\022\021\n\tsectionId\030\001 \001(\003\022\020\n\010" +
				"revision\030\002 \001(\003\022\031\n\007heading\030\003 \001(\0162\010.Headin" +
				"g\022\r\n\005title\030\004 \001(\t\022\017\n\007content\030\005 \001(\tb\006proto" +
				"3"
		};
		descriptor = com.google.protobuf.Descriptors.FileDescriptor
			.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {
					HeadingOuterClass.getDescriptor(),
				});
		internal_static_SectionResponse_descriptor =
			getDescriptor().getMessageTypes().get(0);
		internal_static_SectionResponse_fieldAccessorTable = new
			com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
			internal_static_SectionResponse_descriptor,
			new java.lang.String[] {"SectionId", "Revision", "Heading", "Title", "Content",});
		HeadingOuterClass.getDescriptor();
	}

	// @@protoc_insertion_point(outer_class_scope)
}
