package goorm.eagle7.stelligence.domain.document.content.dto.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DocumentResponse.proto

import static goorm.eagle7.stelligence.domain.document.content.dto.protobuf.SectionResponseOuterClass.*;

import java.util.List;

import goorm.eagle7.stelligence.domain.document.content.model.Document;

/**
 * ProtoBuf을 사용한 DocumentResponse DTO 클래스의 외부 클래스입니다.
 * 코드 전반으로 사용되는 코드를 보기 위해서는 내부 클래스인 DocumentResponse를 확인해주세요.
 */
public final class DocumentResponseOuterClass {

	private DocumentResponseOuterClass() {
	}

	public static void registerAllExtensions(
		com.google.protobuf.ExtensionRegistryLite registry) {
	}

	public static void registerAllExtensions(
		com.google.protobuf.ExtensionRegistry registry) {
		registerAllExtensions(
			(com.google.protobuf.ExtensionRegistryLite)registry);
	}

	public interface DocumentResponseOrBuilder extends
		// @@protoc_insertion_point(interface_extends:DocumentResponse)
		com.google.protobuf.MessageOrBuilder {

		/**
		 * <code>int64 documentId = 1;</code>
		 */
		long getDocumentId();

		/**
		 * <code>string title = 2;</code>
		 */
		java.lang.String getTitle();

		/**
		 * <code>string title = 2;</code>
		 */
		com.google.protobuf.ByteString
		getTitleBytes();

		/**
		 * <pre>
		 * SectionResponse의 리스트
		 * </pre>
		 *
		 * <code>repeated .SectionResponse sections = 3;</code>
		 */
		java.util.List<SectionResponse>
		getSectionsList();

		/**
		 * <pre>
		 * SectionResponse의 리스트
		 * </pre>
		 *
		 * <code>repeated .SectionResponse sections = 3;</code>
		 */
		SectionResponse getSections(int index);

		/**
		 * <pre>
		 * SectionResponse의 리스트
		 * </pre>
		 *
		 * <code>repeated .SectionResponse sections = 3;</code>
		 */
		int getSectionsCount();

		/**
		 * <pre>
		 * SectionResponse의 리스트
		 * </pre>
		 *
		 * <code>repeated .SectionResponse sections = 3;</code>
		 */
		java.util.List<? extends SectionResponseOrBuilder>
		getSectionsOrBuilderList();

		/**
		 * <pre>
		 * SectionResponse의 리스트
		 * </pre>
		 *
		 * <code>repeated .SectionResponse sections = 3;</code>
		 */
		SectionResponseOrBuilder getSectionsOrBuilder(
			int index);
	}

	/**
	 * Protobuf type {@code DocumentResponse}
	 */
	public static final class DocumentResponse extends
		com.google.protobuf.GeneratedMessageV3 implements
		// @@protoc_insertion_point(message_implements:DocumentResponse)
		DocumentResponseOrBuilder {
		private static final long serialVersionUID = 0L;

		//factory method
		public static DocumentResponse of(Document document, List<SectionResponse> sections) {
			return DocumentResponse.newBuilder()
				.setDocumentId(document.getId())
				.setTitle(document.getTitle())
				.addAllSections(sections)
				.build();

		}

		// Use DocumentResponse.newBuilder() to construct.
		private DocumentResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
			super(builder);
		}

		private DocumentResponse() {
			title_ = "";
			sections_ = java.util.Collections.emptyList();
		}

		@java.lang.Override
		@SuppressWarnings({"unused"})
		protected java.lang.Object newInstance(
			UnusedPrivateParameter unused) {
			return new DocumentResponse();
		}

		@java.lang.Override
		public final com.google.protobuf.UnknownFieldSet
		getUnknownFields() {
			return this.unknownFields;
		}

		private DocumentResponse(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			this();
			if (extensionRegistry == null) {
				throw new java.lang.NullPointerException();
			}
			int mutable_bitField0_ = 0;
			com.google.protobuf.UnknownFieldSet.Builder unknownFields =
				com.google.protobuf.UnknownFieldSet.newBuilder();
			try {
				boolean done = false;
				while (!done) {
					int tag = input.readTag();
					switch (tag) {
						case 0:
							done = true;
							break;
						case 8: {

							documentId_ = input.readInt64();
							break;
						}
						case 18: {
							java.lang.String s = input.readStringRequireUtf8();

							title_ = s;
							break;
						}
						case 26: {
							if (!((mutable_bitField0_ & 0x00000001) != 0)) {
								sections_ = new java.util.ArrayList<SectionResponse>();
								mutable_bitField0_ |= 0x00000001;
							}
							sections_.add(
								input.readMessage(SectionResponse.parser(),
									extensionRegistry));
							break;
						}
						default: {
							if (!parseUnknownField(
								input, unknownFields, extensionRegistry, tag)) {
								done = true;
							}
							break;
						}
					}
				}
			} catch (com.google.protobuf.InvalidProtocolBufferException e) {
				throw e.setUnfinishedMessage(this);
			} catch (java.io.IOException e) {
				throw new com.google.protobuf.InvalidProtocolBufferException(
					e).setUnfinishedMessage(this);
			} finally {
				if (((mutable_bitField0_ & 0x00000001) != 0)) {
					sections_ = java.util.Collections.unmodifiableList(sections_);
				}
				this.unknownFields = unknownFields.build();
				makeExtensionsImmutable();
			}
		}

		public static final com.google.protobuf.Descriptors.Descriptor
		getDescriptor() {
			return DocumentResponseOuterClass.internal_static_DocumentResponse_descriptor;
		}

		@java.lang.Override
		protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
		internalGetFieldAccessorTable() {
			return DocumentResponseOuterClass.internal_static_DocumentResponse_fieldAccessorTable
				.ensureFieldAccessorsInitialized(
					DocumentResponseOuterClass.DocumentResponse.class,
					DocumentResponseOuterClass.DocumentResponse.Builder.class);
		}

		public static final int DOCUMENTID_FIELD_NUMBER = 1;
		private long documentId_;

		/**
		 * <code>int64 documentId = 1;</code>
		 */
		public long getDocumentId() {
			return documentId_;
		}

		public static final int TITLE_FIELD_NUMBER = 2;
		private volatile java.lang.Object title_;

		/**
		 * <code>string title = 2;</code>
		 */
		public java.lang.String getTitle() {
			java.lang.Object ref = title_;
			if (ref instanceof java.lang.String) {
				return (java.lang.String)ref;
			} else {
				com.google.protobuf.ByteString bs =
					(com.google.protobuf.ByteString)ref;
				java.lang.String s = bs.toStringUtf8();
				title_ = s;
				return s;
			}
		}

		/**
		 * <code>string title = 2;</code>
		 */
		public com.google.protobuf.ByteString
		getTitleBytes() {
			java.lang.Object ref = title_;
			if (ref instanceof java.lang.String) {
				com.google.protobuf.ByteString b =
					com.google.protobuf.ByteString.copyFromUtf8(
						(java.lang.String)ref);
				title_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString)ref;
			}
		}

		@Override
		public List<SectionResponse> getSectionsList() {
			return null;
		}

		public static final int SECTIONS_FIELD_NUMBER = 3;
		private java.util.List<SectionResponse> sections_;

		/**
		 * <pre>
		 * SectionResponse의 리스트
		 * </pre>
		 *
		 * <code>repeated .SectionResponse sections = 3;</code>
		 */
		public java.util.List<SectionResponse> getSections() {
			return sections_;
		}

		/**
		 * <pre>
		 * SectionResponse의 리스트
		 * </pre>
		 *
		 * <code>repeated .SectionResponse sections = 3;</code>
		 */
		public java.util.List<? extends SectionResponseOrBuilder>
		getSectionsOrBuilderList() {
			return sections_;
		}

		/**
		 * <pre>
		 * SectionResponse의 리스트
		 * </pre>
		 *
		 * <code>repeated .SectionResponse sections = 3;</code>
		 */
		public int getSectionsCount() {
			return sections_.size();
		}

		/**
		 * <pre>
		 * SectionResponse의 리스트
		 * </pre>
		 *
		 * <code>repeated .SectionResponse sections = 3;</code>
		 */
		public SectionResponse getSections(int index) {
			return sections_.get(index);
		}

		/**
		 * <pre>
		 * SectionResponse의 리스트
		 * </pre>
		 *
		 * <code>repeated .SectionResponse sections = 3;</code>
		 */
		public SectionResponseOrBuilder getSectionsOrBuilder(
			int index) {
			return sections_.get(index);
		}

		private byte memoizedIsInitialized = -1;

		@java.lang.Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized == 1)
				return true;
			if (isInitialized == 0)
				return false;

			memoizedIsInitialized = 1;
			return true;
		}

		@java.lang.Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
			throws java.io.IOException {
			if (documentId_ != 0L) {
				output.writeInt64(1, documentId_);
			}
			if (!getTitleBytes().isEmpty()) {
				com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
			}
			for (int i = 0; i < sections_.size(); i++) {
				output.writeMessage(3, sections_.get(i));
			}
			unknownFields.writeTo(output);
		}

		@java.lang.Override
		public int getSerializedSize() {
			int size = memoizedSize;
			if (size != -1)
				return size;

			size = 0;
			if (documentId_ != 0L) {
				size += com.google.protobuf.CodedOutputStream
					.computeInt64Size(1, documentId_);
			}
			if (!getTitleBytes().isEmpty()) {
				size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
			}
			for (int i = 0; i < sections_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
					.computeMessageSize(3, sections_.get(i));
			}
			size += unknownFields.getSerializedSize();
			memoizedSize = size;
			return size;
		}

		@java.lang.Override
		public boolean equals(final java.lang.Object obj) {
			if (obj == this) {
				return true;
			}
			if (!(obj instanceof DocumentResponseOuterClass.DocumentResponse)) {
				return super.equals(obj);
			}
			DocumentResponseOuterClass.DocumentResponse other = (DocumentResponseOuterClass.DocumentResponse)obj;

			if (getDocumentId()
				!= other.getDocumentId())
				return false;
			if (!getTitle()
				.equals(other.getTitle()))
				return false;
			if (!getSectionsList()
				.equals(other.getSectionsList()))
				return false;
			if (!unknownFields.equals(other.unknownFields))
				return false;
			return true;
		}

		@java.lang.Override
		public int hashCode() {
			if (memoizedHashCode != 0) {
				return memoizedHashCode;
			}
			int hash = 41;
			hash = (19 * hash) + getDescriptor().hashCode();
			hash = (37 * hash) + DOCUMENTID_FIELD_NUMBER;
			hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
				getDocumentId());
			hash = (37 * hash) + TITLE_FIELD_NUMBER;
			hash = (53 * hash) + getTitle().hashCode();
			if (getSectionsCount() > 0) {
				hash = (37 * hash) + SECTIONS_FIELD_NUMBER;
				hash = (53 * hash) + getSectionsList().hashCode();
			}
			hash = (29 * hash) + unknownFields.hashCode();
			memoizedHashCode = hash;
			return hash;
		}

		public static DocumentResponseOuterClass.DocumentResponse parseFrom(
			java.nio.ByteBuffer data)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static DocumentResponseOuterClass.DocumentResponse parseFrom(
			java.nio.ByteBuffer data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static DocumentResponseOuterClass.DocumentResponse parseFrom(
			com.google.protobuf.ByteString data)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static DocumentResponseOuterClass.DocumentResponse parseFrom(
			com.google.protobuf.ByteString data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static DocumentResponseOuterClass.DocumentResponse parseFrom(byte[] data)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data);
		}

		public static DocumentResponseOuterClass.DocumentResponse parseFrom(
			byte[] data,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws com.google.protobuf.InvalidProtocolBufferException {
			return PARSER.parseFrom(data, extensionRegistry);
		}

		public static DocumentResponseOuterClass.DocumentResponse parseFrom(java.io.InputStream input)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input);
		}

		public static DocumentResponseOuterClass.DocumentResponse parseFrom(
			java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input, extensionRegistry);
		}

		public static DocumentResponseOuterClass.DocumentResponse parseDelimitedFrom(java.io.InputStream input)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseDelimitedWithIOException(PARSER, input);
		}

		public static DocumentResponseOuterClass.DocumentResponse parseDelimitedFrom(
			java.io.InputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
		}

		public static DocumentResponseOuterClass.DocumentResponse parseFrom(
			com.google.protobuf.CodedInputStream input)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input);
		}

		public static DocumentResponseOuterClass.DocumentResponse parseFrom(
			com.google.protobuf.CodedInputStream input,
			com.google.protobuf.ExtensionRegistryLite extensionRegistry)
			throws java.io.IOException {
			return com.google.protobuf.GeneratedMessageV3
				.parseWithIOException(PARSER, input, extensionRegistry);
		}

		@java.lang.Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder() {
			return DEFAULT_INSTANCE.toBuilder();
		}

		public static Builder newBuilder(DocumentResponseOuterClass.DocumentResponse prototype) {
			return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
		}

		@java.lang.Override
		public Builder toBuilder() {
			return this == DEFAULT_INSTANCE
				? new Builder() : new Builder().mergeFrom(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
			com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		/**
		 * Protobuf type {@code DocumentResponse}
		 */
		public static final class Builder extends
			com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
			// @@protoc_insertion_point(builder_implements:DocumentResponse)
			DocumentResponseOuterClass.DocumentResponseOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
			getDescriptor() {
				return DocumentResponseOuterClass.internal_static_DocumentResponse_descriptor;
			}

			@java.lang.Override
			protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
			internalGetFieldAccessorTable() {
				return DocumentResponseOuterClass.internal_static_DocumentResponse_fieldAccessorTable
					.ensureFieldAccessorsInitialized(
						DocumentResponseOuterClass.DocumentResponse.class,
						DocumentResponseOuterClass.DocumentResponse.Builder.class);
			}

			// Construct using DocumentResponseOuterClass.DocumentResponse.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(
				com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessageV3
					.alwaysUseFieldBuilders) {
					getSectionsFieldBuilder();
				}
			}

			@java.lang.Override
			public Builder clear() {
				super.clear();
				documentId_ = 0L;

				title_ = "";

				if (sectionsBuilder_ == null) {
					sections_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
				} else {
					sectionsBuilder_.clear();
				}
				return this;
			}

			@java.lang.Override
			public com.google.protobuf.Descriptors.Descriptor
			getDescriptorForType() {
				return DocumentResponseOuterClass.internal_static_DocumentResponse_descriptor;
			}

			@java.lang.Override
			public DocumentResponseOuterClass.DocumentResponse getDefaultInstanceForType() {
				return DocumentResponseOuterClass.DocumentResponse.getDefaultInstance();
			}

			@java.lang.Override
			public DocumentResponseOuterClass.DocumentResponse build() {
				DocumentResponseOuterClass.DocumentResponse result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			@java.lang.Override
			public DocumentResponseOuterClass.DocumentResponse buildPartial() {
				DocumentResponseOuterClass.DocumentResponse result = new DocumentResponseOuterClass.DocumentResponse(
					this);
				int from_bitField0_ = bitField0_;
				result.documentId_ = documentId_;
				result.title_ = title_;
				if (sectionsBuilder_ == null) {
					if (((bitField0_ & 0x00000001) != 0)) {
						sections_ = java.util.Collections.unmodifiableList(sections_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.sections_ = sections_;
				} else {
					result.sections_ = sectionsBuilder_.build();
				}
				onBuilt();
				return result;
			}

			@java.lang.Override
			public Builder clone() {
				return super.clone();
			}

			@java.lang.Override
			public Builder setField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				java.lang.Object value) {
				return super.setField(field, value);
			}

			@java.lang.Override
			public Builder clearField(
				com.google.protobuf.Descriptors.FieldDescriptor field) {
				return super.clearField(field);
			}

			@java.lang.Override
			public Builder clearOneof(
				com.google.protobuf.Descriptors.OneofDescriptor oneof) {
				return super.clearOneof(oneof);
			}

			@java.lang.Override
			public Builder setRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				int index, java.lang.Object value) {
				return super.setRepeatedField(field, index, value);
			}

			@java.lang.Override
			public Builder addRepeatedField(
				com.google.protobuf.Descriptors.FieldDescriptor field,
				java.lang.Object value) {
				return super.addRepeatedField(field, value);
			}

			@java.lang.Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof DocumentResponseOuterClass.DocumentResponse) {
					return mergeFrom((DocumentResponseOuterClass.DocumentResponse)other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(DocumentResponseOuterClass.DocumentResponse other) {
				if (other == DocumentResponseOuterClass.DocumentResponse.getDefaultInstance())
					return this;
				if (other.getDocumentId() != 0L) {
					setDocumentId(other.getDocumentId());
				}
				if (!other.getTitle().isEmpty()) {
					title_ = other.title_;
					onChanged();
				}
				if (sectionsBuilder_ == null) {
					if (!other.sections_.isEmpty()) {
						if (sections_.isEmpty()) {
							sections_ = other.sections_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureSectionsIsMutable();
							sections_.addAll(other.sections_);
						}
						onChanged();
					}
				} else {
					if (!other.sections_.isEmpty()) {
						if (sectionsBuilder_.isEmpty()) {
							sectionsBuilder_.dispose();
							sectionsBuilder_ = null;
							sections_ = other.sections_;
							bitField0_ = (bitField0_ & ~0x00000001);
							sectionsBuilder_ =
								com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
									getSectionsFieldBuilder() : null;
						} else {
							sectionsBuilder_.addAllMessages(other.sections_);
						}
					}
				}
				this.mergeUnknownFields(other.unknownFields);
				onChanged();
				return this;
			}

			@java.lang.Override
			public final boolean isInitialized() {
				return true;
			}

			@java.lang.Override
			public Builder mergeFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
				DocumentResponseOuterClass.DocumentResponse parsedMessage = null;
				try {
					parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
				} catch (com.google.protobuf.InvalidProtocolBufferException e) {
					parsedMessage = (DocumentResponseOuterClass.DocumentResponse)e.getUnfinishedMessage();
					throw e.unwrapIOException();
				} finally {
					if (parsedMessage != null) {
						mergeFrom(parsedMessage);
					}
				}
				return this;
			}

			private int bitField0_;

			private long documentId_;

			/**
			 * <code>int64 documentId = 1;</code>
			 */
			public long getDocumentId() {
				return documentId_;
			}

			/**
			 * <code>int64 documentId = 1;</code>
			 */
			public Builder setDocumentId(long value) {

				documentId_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>int64 documentId = 1;</code>
			 */
			public Builder clearDocumentId() {

				documentId_ = 0L;
				onChanged();
				return this;
			}

			private java.lang.Object title_ = "";

			/**
			 * <code>string title = 2;</code>
			 */
			public java.lang.String getTitle() {
				java.lang.Object ref = title_;
				if (!(ref instanceof java.lang.String)) {
					com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString)ref;
					java.lang.String s = bs.toStringUtf8();
					title_ = s;
					return s;
				} else {
					return (java.lang.String)ref;
				}
			}

			/**
			 * <code>string title = 2;</code>
			 */
			public com.google.protobuf.ByteString
			getTitleBytes() {
				java.lang.Object ref = title_;
				if (ref instanceof String) {
					com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8(
							(java.lang.String)ref);
					title_ = b;
					return b;
				} else {
					return (com.google.protobuf.ByteString)ref;
				}
			}

			/**
			 * <code>string title = 2;</code>
			 */
			public Builder setTitle(
				java.lang.String value) {
				if (value == null) {
					throw new NullPointerException();
				}

				title_ = value;
				onChanged();
				return this;
			}

			/**
			 * <code>string title = 2;</code>
			 */
			public Builder clearTitle() {

				title_ = getDefaultInstance().getTitle();
				onChanged();
				return this;
			}

			/**
			 * <code>string title = 2;</code>
			 */
			public Builder setTitleBytes(
				com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				checkByteStringIsUtf8(value);

				title_ = value;
				onChanged();
				return this;
			}

			private java.util.List<SectionResponse> sections_ =
				java.util.Collections.emptyList();

			private void ensureSectionsIsMutable() {
				if (!((bitField0_ & 0x00000001) != 0)) {
					sections_ = new java.util.ArrayList<SectionResponse>(sections_);
					bitField0_ |= 0x00000001;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilderV3<
				SectionResponse, SectionResponse.Builder, SectionResponseOrBuilder> sectionsBuilder_;

			/**
			 * <pre>
			 * SectionResponse의 리스트
			 * </pre>
			 *
			 * <code>repeated .SectionResponse sections = 3;</code>
			 */
			public java.util.List<SectionResponse> getSectionsList() {
				if (sectionsBuilder_ == null) {
					return java.util.Collections.unmodifiableList(sections_);
				} else {
					return sectionsBuilder_.getMessageList();
				}
			}

			/**
			 * <pre>
			 * SectionResponse의 리스트
			 * </pre>
			 *
			 * <code>repeated .SectionResponse sections = 3;</code>
			 */
			public int getSectionsCount() {
				if (sectionsBuilder_ == null) {
					return sections_.size();
				} else {
					return sectionsBuilder_.getCount();
				}
			}

			/**
			 * <pre>
			 * SectionResponse의 리스트
			 * </pre>
			 *
			 * <code>repeated .SectionResponse sections = 3;</code>
			 */
			public SectionResponse getSections(int index) {
				if (sectionsBuilder_ == null) {
					return sections_.get(index);
				} else {
					return sectionsBuilder_.getMessage(index);
				}
			}

			/**
			 * <pre>
			 * SectionResponse의 리스트
			 * </pre>
			 *
			 * <code>repeated .SectionResponse sections = 3;</code>
			 */
			public Builder setSections(
				int index, SectionResponse value) {
				if (sectionsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureSectionsIsMutable();
					sections_.set(index, value);
					onChanged();
				} else {
					sectionsBuilder_.setMessage(index, value);
				}
				return this;
			}

			/**
			 * <pre>
			 * SectionResponse의 리스트
			 * </pre>
			 *
			 * <code>repeated .SectionResponse sections = 3;</code>
			 */
			public Builder setSections(
				int index, SectionResponse.Builder builderForValue) {
				if (sectionsBuilder_ == null) {
					ensureSectionsIsMutable();
					sections_.set(index, builderForValue.build());
					onChanged();
				} else {
					sectionsBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <pre>
			 * SectionResponse의 리스트
			 * </pre>
			 *
			 * <code>repeated .SectionResponse sections = 3;</code>
			 */
			public Builder addSections(SectionResponse value) {
				if (sectionsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureSectionsIsMutable();
					sections_.add(value);
					onChanged();
				} else {
					sectionsBuilder_.addMessage(value);
				}
				return this;
			}

			/**
			 * <pre>
			 * SectionResponse의 리스트
			 * </pre>
			 *
			 * <code>repeated .SectionResponse sections = 3;</code>
			 */
			public Builder addSections(
				int index, SectionResponse value) {
				if (sectionsBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureSectionsIsMutable();
					sections_.add(index, value);
					onChanged();
				} else {
					sectionsBuilder_.addMessage(index, value);
				}
				return this;
			}

			/**
			 * <pre>
			 * SectionResponse의 리스트
			 * </pre>
			 *
			 * <code>repeated .SectionResponse sections = 3;</code>
			 */
			public Builder addSections(
				SectionResponse.Builder builderForValue) {
				if (sectionsBuilder_ == null) {
					ensureSectionsIsMutable();
					sections_.add(builderForValue.build());
					onChanged();
				} else {
					sectionsBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			/**
			 * <pre>
			 * SectionResponse의 리스트
			 * </pre>
			 *
			 * <code>repeated .SectionResponse sections = 3;</code>
			 */
			public Builder addSections(
				int index, SectionResponse.Builder builderForValue) {
				if (sectionsBuilder_ == null) {
					ensureSectionsIsMutable();
					sections_.add(index, builderForValue.build());
					onChanged();
				} else {
					sectionsBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			/**
			 * <pre>
			 * SectionResponse의 리스트
			 * </pre>
			 *
			 * <code>repeated .SectionResponse sections = 3;</code>
			 */
			public Builder addAllSections(
				java.lang.Iterable<? extends SectionResponse> values) {
				if (sectionsBuilder_ == null) {
					ensureSectionsIsMutable();
					com.google.protobuf.AbstractMessageLite.Builder.addAll(
						values, sections_);
					onChanged();
				} else {
					sectionsBuilder_.addAllMessages(values);
				}
				return this;
			}

			/**
			 * <pre>
			 * SectionResponse의 리스트
			 * </pre>
			 *
			 * <code>repeated .SectionResponse sections = 3;</code>
			 */
			public Builder clearSections() {
				if (sectionsBuilder_ == null) {
					sections_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					sectionsBuilder_.clear();
				}
				return this;
			}

			/**
			 * <pre>
			 * SectionResponse의 리스트
			 * </pre>
			 *
			 * <code>repeated .SectionResponse sections = 3;</code>
			 */
			public Builder removeSections(int index) {
				if (sectionsBuilder_ == null) {
					ensureSectionsIsMutable();
					sections_.remove(index);
					onChanged();
				} else {
					sectionsBuilder_.remove(index);
				}
				return this;
			}

			/**
			 * <pre>
			 * SectionResponse의 리스트
			 * </pre>
			 *
			 * <code>repeated .SectionResponse sections = 3;</code>
			 */
			public SectionResponse.Builder getSectionsBuilder(
				int index) {
				return getSectionsFieldBuilder().getBuilder(index);
			}

			/**
			 * <pre>
			 * SectionResponse의 리스트
			 * </pre>
			 *
			 * <code>repeated .SectionResponse sections = 3;</code>
			 */
			public SectionResponseOrBuilder getSectionsOrBuilder(
				int index) {
				if (sectionsBuilder_ == null) {
					return sections_.get(index);
				} else {
					return sectionsBuilder_.getMessageOrBuilder(index);
				}
			}

			/**
			 * <pre>
			 * SectionResponse의 리스트
			 * </pre>
			 *
			 * <code>repeated .SectionResponse sections = 3;</code>
			 */
			public java.util.List<? extends SectionResponseOrBuilder>
			getSectionsOrBuilderList() {
				if (sectionsBuilder_ != null) {
					return sectionsBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(sections_);
				}
			}

			/**
			 * <pre>
			 * SectionResponse의 리스트
			 * </pre>
			 *
			 * <code>repeated .SectionResponse sections = 3;</code>
			 */
			public SectionResponse.Builder addSectionsBuilder() {
				return getSectionsFieldBuilder().addBuilder(
					SectionResponse.getDefaultInstance());
			}

			/**
			 * <pre>
			 * SectionResponse의 리스트
			 * </pre>
			 *
			 * <code>repeated .SectionResponse sections = 3;</code>
			 */
			public SectionResponse.Builder addSectionsBuilder(
				int index) {
				return getSectionsFieldBuilder().addBuilder(
					index, SectionResponse.getDefaultInstance());
			}

			/**
			 * <pre>
			 * SectionResponse의 리스트
			 * </pre>
			 *
			 * <code>repeated .SectionResponse sections = 3;</code>
			 */
			public java.util.List<SectionResponse.Builder>
			getSectionsBuilderList() {
				return getSectionsFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilderV3<
				SectionResponse, SectionResponse.Builder, SectionResponseOrBuilder>
			getSectionsFieldBuilder() {
				if (sectionsBuilder_ == null) {
					sectionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
						SectionResponse, SectionResponse.Builder, SectionResponseOrBuilder>(
						sections_,
						((bitField0_ & 0x00000001) != 0),
						getParentForChildren(),
						isClean());
					sections_ = null;
				}
				return sectionsBuilder_;
			}

			@java.lang.Override
			public final Builder setUnknownFields(
				final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.setUnknownFields(unknownFields);
			}

			@java.lang.Override
			public final Builder mergeUnknownFields(
				final com.google.protobuf.UnknownFieldSet unknownFields) {
				return super.mergeUnknownFields(unknownFields);
			}

			// @@protoc_insertion_point(builder_scope:DocumentResponse)
		}

		// @@protoc_insertion_point(class_scope:DocumentResponse)
		private static final DocumentResponseOuterClass.DocumentResponse DEFAULT_INSTANCE;

		static {
			DEFAULT_INSTANCE = new DocumentResponseOuterClass.DocumentResponse();
		}

		public static DocumentResponseOuterClass.DocumentResponse getDefaultInstance() {
			return DEFAULT_INSTANCE;
		}

		private static final com.google.protobuf.Parser<DocumentResponse>
			PARSER = new com.google.protobuf.AbstractParser<DocumentResponse>() {
			@java.lang.Override
			public DocumentResponse parsePartialFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
				return new DocumentResponse(input, extensionRegistry);
			}
		};

		public static com.google.protobuf.Parser<DocumentResponse> parser() {
			return PARSER;
		}

		@java.lang.Override
		public com.google.protobuf.Parser<DocumentResponse> getParserForType() {
			return PARSER;
		}

		@java.lang.Override
		public DocumentResponseOuterClass.DocumentResponse getDefaultInstanceForType() {
			return DEFAULT_INSTANCE;
		}

	}

	private static final com.google.protobuf.Descriptors.Descriptor
		internal_static_DocumentResponse_descriptor;
	private static final
	com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
		internal_static_DocumentResponse_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor
	getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor
		descriptor;

	static {
		java.lang.String[] descriptorData = {
			"\n\026DocumentResponse.proto\032\025SectionRespons" +
				"e.proto\"Y\n\020DocumentResponse\022\022\n\ndocumentI" +
				"d\030\001 \001(\003\022\r\n\005title\030\002 \001(\t\022\"\n\010sections\030\003 \003(\013" +
				"2\020.SectionResponseb\006proto3"
		};
		descriptor = com.google.protobuf.Descriptors.FileDescriptor
			.internalBuildGeneratedFileFrom(descriptorData,
				new com.google.protobuf.Descriptors.FileDescriptor[] {
					SectionResponseOuterClass.getDescriptor(),
				});
		internal_static_DocumentResponse_descriptor =
			getDescriptor().getMessageTypes().get(0);
		internal_static_DocumentResponse_fieldAccessorTable = new
			com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
			internal_static_DocumentResponse_descriptor,
			new java.lang.String[] {"DocumentId", "Title", "Sections",});
		SectionResponseOuterClass.getDescriptor();
	}

	// @@protoc_insertion_point(outer_class_scope)
}
